config/routes.rb
Rails.application.routes.draw do

  get 'uploader/index'

  get 'uploader/form'

  post 'uploader/upload'

  get 'uploader/download'

  root to: 'homes#top'

  get 'homes/top'

  get 'homes/about'

  get 'homes/flow'

  get 'homes/photos'

  get 'homes/staffs'

  get 'homes/login'

  resources :inquiry do
    collection do
      post :confirm
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :admin do
    resources :order
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
  has_many :picures
  validates :name, presence: true
  validates :phone_number, presence: true
  validates :mail ,presence: true
end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :image_id, ImageUploader
  belongs_to :inquiry
end

app/models/upload_file.rb
class UploadFile < ApplicationRecord
end

app/controllers/admin/order_controller.rb
class Admin::OrderController < ApplicationController
  def index
    @order = Inquiry.all
  end
  def show
    @order = Inquiry.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end

  def flow
  end

  def photos
  end

  def staffs
  end

  def login
  end

end

app/controllers/inquiry_controller.rb
class InquiryController < ApplicationController
  def index
    @inquiry = Inquiry.new
  end

  def confirm
    # POSTされたパラメータを取得
    @inquiry = Inquiry.new(inquiry_params)
    # バリデーションチェックNGなら戻す
    render :index if @inquiry.invalid?
  end

  def create
    inquiry = Inquiry.new(inquiry_params)
    if params[:back]
      render :index
    elsif inquiry.save
      redirect_to inquiry_path(id: inquiry.id),notice: "申し込みが完了しました。"
    else
      render :index
    end
  end

  def show
  end

  private
  #セキュリティのため、permitメソッドで許可したパラメータ名しか取得できない。
    def inquiry_params
      params.require(:inquiry).permit(:campaign_code,:genre,:area,:place_decide_which,:date,:name,:phone_number,:mail,:comment,:line_id,:option)
    end

end

app/controllers/uploader_controller.rb
class UploaderController < ApplicationController
  def index
  end

  def form
  end

  def upload
    @upload_file = UploadFile.new(uploader_params)
    @upload_file.save
    redirect_to action: 'index'
  end

  def download
    @upload_file = UploadFile.find(params[:id].to_i)
    filepath = @upload_file.file.current_path
    stat = File::stat(filepath)
    send_file(filepath, :filename => @upload_file.file.url.gsub(/.*\//,''), length => stat.size)
  end

  private
  def uploader_params
    params.require(:upload_file).permit(:name, :file)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/inquiry_helper.rb
module InquiryHelper
end

app/helpers/uploader_helper.rb
module UploaderHelper
end

app/views/admin/order/index.html.erb
<h1>管理画面です</h1>
<% @order.each do |order| %>
  <p>名前</p>
  <span>
    <%= link_to order.name, admin_order_path(order.id) %>
  </span>
  <p>電話番号</p>
  <span><%= order.phone_number %></span>
  <p>メールアドレス</p>
  <span><%= order.mail %></span>
<% end %>

app/views/admin/order/show.html.erb
<h1>詳細管理画面です。</h1>
<h1>名前</h1>
<%= @order.name %>
<h1>電話番号</h1>
<%= @order.phone_number %>
<h1>メールアドレス</h1>
<%= @order.mail %>

<%= link_to '納品画面へ' ,uploader_form_path %>

app/views/homes/_footer.html.erb
<footer class="footer">
  <div class="container">
    <p class="text-muted">
      <font style="vertical-align: inherit;">
        <font style="vertical-align: inherit;">ここには固定フッターのコンテンツを配置します。</font>
      </font>
    </p>
  </div>
</footer>

app/views/homes/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'LOVE GRAPH', homes_top_path, class: "navbar-brand" %>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to 'ABOUT', homes_about_path %></li>
            <li><%= link_to 'FLOW', homes_flow_path %></li>
            <li><%= link_to 'PHOTOS', homes_photos_path %></li>
            <li><%= link_to 'STAFFS', homes_staffs_path %></li>
            <li><%= link_to 'LOGIN', homes_login_path %></li>
            <li><%= link_to '撮影申し込み', inquiry_index_path %></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

app/views/homes/about.html.erb
<%= render "header" %>
<h1>Homes#about</h1>
<p>Find me in app/views/homes/about.html.erb</p>

app/views/homes/flow.html.erb
<%= render "header" %>
<h1>Homes#flow</h1>
<p>Find me in app/views/homes/flow.html.erb</p>
<%= render "footer" %>

app/views/homes/login.html.erb
<%= render "header" %>
<h1>Homes#login</h1>
<p>Find me in app/views/homes/login.html.erb</p>
<%= render "footer" %>

app/views/homes/photos.html.erb
<%= render "header" %>
<h1>Homes#photos</h1>
<p>Find me in app/views/homes/photos.html.erb</p>
<%= render "footer" %>

app/views/homes/staffs.html.erb
<%= render "header" %>
<h1>Homes#staffs</h1>
<p>Find me in app/views/homes/staffs.html.erb</p>
<%= render "footer" %>

app/views/homes/top.html.erb
<%= render "header" %>
<h1>Homes#top</h1>
<p>Find me in app/views/homes/top.html.erb</p>
<%= render "footer" %>

app/views/inquiry/confirm.html.erb
<div class="container">
  <%= form_for @inquiry, :url => { :controller => :inquiry, :action => :create} do |f| %>
  <div class="form-group">
    名前: <%= @inquiry.name %><br>
    <%= f.hidden_field :name %>
  </div>
  <div class="form-group">
    電話番号: <%= @inquiry.phone_number %><br>
    <%= f.hidden_field :phone_number %>
  </div>
  <div class="form-group">
    メールアドレス: <%= @inquiry.mail %><br>
    <%= f.hidden_field :mail %>
  </div>

  <%= f.submit '戻る' ,name: 'back'%>
  <%= f.submit '申し込み完了'%>
  <% end %>
</div>

app/views/inquiry/index.html.erb
<div class="container">
  <%= form_for @inquiry, :url => { :controller => :inquiry, :action => :confirm } do |f| %>
  <div class="form-group">
    <%= f.label :name,"名前" %><br>
    <%= f.text_field :name %>
  </div>
  <div class="form-group">
    <%= f.label :phone_number ,"電話番号"%><br>
    <%= f.text_field :phone_number %>
  </div>
  <div class="form-group">
    <%= f.label :mail ,"メールアドレス" %><br>
    <%= f.text_field :mail %>
  </div>

  <%= f.submit '内容の確認に進む'%>
  <% end %>
</div>

app/views/inquiry/show.html.erb
申し込みが完了しました!
おめでとうございます。
<br>
<%= link_to 'ホームに戻る', homes_top_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LovegraphIntern</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/uploader/download.html.erb
<h1>Uploader#download</h1>
<p>Find me in app/views/uploader/download.html.erb</p>

app/views/uploader/form.html.erb
<% @upload = UploadFile.new %>
<%= form_for @upload, :url => {:action => :upload} do |f| %>
  <%= f.label :name, "name" %>
  <%= f.text_field :name %>
  <%= f.label :file %>
  <%= f.file_field :file %>
  <%= f.submit "Upload" %>
<% end %>

app/views/uploader/index.html.erb
<%= link_to 'アップロードはこちら', action: "form" %>
<ul>
  <% UploadFile.all.reverse_order.each do |upload| %>
    <li><%= link_to upload.name, action: "download", id:upload.id %></li>
  <% end %>
</ul>

app/views/uploader/upload.html.erb
<h1>Uploader#upload</h1>
<p>Find me in app/views/uploader/upload.html.erb</p>